### ISSUE TITLE
Latest patch broke FreeStuff mod 

### ISSUE THREAD

**Issue by dmikon** [captncraig/DysonMods#1]
Hi Cap Craig,

Could You please fix it.
Thanks in advance.

BR, D.K.

**Comment by 5thHorseman** [comment]
This is working fine in 0.8.21.8562

**Comment by tryst46** [comment]
Broken for me too. Can create a filter but nothing comes out.
v0.8.21.8562

Any possible conflicts?

**Comment by dirky-storm** [comment]
> Broken for me too. Can create a filter but nothing comes out. v0.8.21.8562
> 
> Any possible conflicts?

It only works when there is one single output belt, could it be there are more than one belts connected?

**Comment by tryst46** [comment]
> > Broken for me too. Can create a filter but nothing comes out. v0.8.21.8562
> > Any possible conflicts?
> 
> It only works when there is one single output belt, could it be there are more than one belts connected?
No, only one belt.
